name: Publish Package to GitHub NPM Registry

on: push
  
    
jobs:
    npm-package:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
        - name: install/set up NodeJS
          uses: actions/setup-node@v4
          with:
            node-version: '20.x'
            registry-url: 'https://registry.npmjs.org'
        - name: npm install
          run: npm install
          
          
